modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="manyideas_core_patch"
    version="1.0.0"
    displayName="Many Ideas Core Server Patch"
    authors="FTTristan"
    description="Fixes the Dedicated Server crash."

[[dependencies.manyideas_core_patch]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.manyideas_core_patch]]
    modId="manyideas_core"
    mandatory=true
    versionRange="[1.4.2]"
    ordering="AFTER"
    side="BOTH"